# Checkov skip configuration for hakoniwa

skip-path:
  - charts/ # Skip for now as it is fully unrendered to start

skip-check:
  - CKV_DOCKER_7 # Chainguard images non versioned tags
  - CKV_DOCKER_2 # App specific HEALTHCHECK
  - CKV_DOCKER_3 # Chainguard runtime images run as nonroot by default
  - CKV_SECRET_6 # False positives on placeholders