{{- range .Values.persistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "single-container.name" $ }}-{{ .name }}
  labels:
    {{- include "single-container.labels" $ | nindent 4 }}
spec:
  accessModes:
    {{- if .accessModes }}
    {{- toYaml .accessModes | nindent 4 }}
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  {{- if .storageClass }}
  storageClassName: {{ .storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}