{{- if and .Values.tailscale .Values.tailscale.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "single-container.name" . }}-tailscale
  labels:
    {{- include "single-container.labels" . | nindent 4 }}
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - {{ .Values.tailscale.hostname | default (include "single-container.name" .) }}
  defaultBackend:
    service:
      name: {{ include "single-container.name" . }}
      port:
        number: 80
{{- end }}
