name: Release Binaries

on:
  workflow_call:
    inputs:
      new_version:
        description: "The version tag to upload binaries for"
        type: string
        required: true
      binary-name:
        description: "Name of the binary to upload"
        type: string
        required: true
      targets:
        description: 'JSON array of targets, e.g. ["x86_64-unknown-linux-gnu","aarch64-unknown-linux-gnu"]'
        type: string
        default: '["x86_64-unknown-linux-gnu"]'

permissions:
  contents: write

jobs:
  binaries:
    name: Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{ fromJson(inputs.targets) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Upload binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ inputs.binary-name }}
          target: ${{ matrix.target }}
          archive: $bin-${{ matrix.target }}
          ref: refs/tags/v${{ inputs.new_version }}
          token: ${{ steps.app-token.outputs.token }}
